// <auto-generated />
using System;
using FastFoodRestaurant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FastFoodRestaurant.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Carrito", b =>
                {
                    b.Property<int>("carrito_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Tbl_Combomenu_id")
                        .HasColumnType("int");

                    b.Property<int?>("Tbl_Productoproducto_id")
                        .HasColumnType("int");

                    b.Property<int?>("Tbl_Userusuario_id")
                        .HasColumnType("int");

                    b.Property<int>("cantidadP")
                        .HasColumnType("int");

                    b.Property<int>("combo_FK")
                        .HasColumnType("int");

                    b.Property<int>("producto_Fk")
                        .HasColumnType("int");

                    b.Property<double>("totalP")
                        .HasColumnType("float");

                    b.Property<int>("usuario_FK")
                        .HasColumnType("int");

                    b.HasKey("carrito_id");

                    b.HasIndex("Tbl_Combomenu_id");

                    b.HasIndex("Tbl_Productoproducto_id");

                    b.HasIndex("Tbl_Userusuario_id");

                    b.ToTable("tbl_Carrito");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Combo", b =>
                {
                    b.Property<int>("menu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("codCombo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estadoCombo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaCreacionC")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombreCombo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precioC")
                        .HasColumnType("float");

                    b.HasKey("menu_id");

                    b.ToTable("tbl_Combo");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_DetalleCombo", b =>
                {
                    b.Property<int>("detalleCombo_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Tbl_Combomenu_id")
                        .HasColumnType("int");

                    b.Property<int?>("Tbl_Productoproducto_id")
                        .HasColumnType("int");

                    b.Property<int>("cantidadP")
                        .HasColumnType("int");

                    b.Property<int>("combo_FK")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("producto_Fk")
                        .HasColumnType("int");

                    b.HasKey("detalleCombo_id");

                    b.HasIndex("Tbl_Combomenu_id");

                    b.HasIndex("Tbl_Productoproducto_id");

                    b.ToTable("tbl_DetalleCombo");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_DetalleOrden", b =>
                {
                    b.Property<int>("detalleOden_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Tbl_Combomenu_id")
                        .HasColumnType("int");

                    b.Property<int?>("Tbl_Ordenorden_id")
                        .HasColumnType("int");

                    b.Property<int?>("Tbl_Productoproducto_id")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("combo_FK")
                        .HasColumnType("int");

                    b.Property<int>("orden_FK")
                        .HasColumnType("int");

                    b.Property<int>("producto_Fk")
                        .HasColumnType("int");

                    b.Property<double>("totalFinal")
                        .HasColumnType("float");

                    b.HasKey("detalleOden_id");

                    b.HasIndex("Tbl_Combomenu_id");

                    b.HasIndex("Tbl_Ordenorden_id");

                    b.HasIndex("Tbl_Productoproducto_id");

                    b.ToTable("tbl_DetalleOrden");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Documento", b =>
                {
                    b.Property<int>("documento_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("documento_id");

                    b.ToTable("tbl_Documento");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Domicilio", b =>
                {
                    b.Property<int>("domicilio_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("referencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("usuario_Fk")
                        .HasColumnType("int");

                    b.HasKey("domicilio_id");

                    b.ToTable("tbl_Domicilio");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Menu", b =>
                {
                    b.Property<int>("menu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreMenu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("menu_id");

                    b.ToTable("tbl_Menu");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_MetodoPago", b =>
                {
                    b.Property<int>("metodoPago_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreMetodo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("metodoPago_id");

                    b.ToTable("tbl_MetodoPago");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Orden", b =>
                {
                    b.Property<int>("orden_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Tbl_Documentodocumento_id")
                        .HasColumnType("int");

                    b.Property<int?>("Tbl_MetodoPagometodoPago_id")
                        .HasColumnType("int");

                    b.Property<int?>("Tbl_Userusuario_id")
                        .HasColumnType("int");

                    b.Property<string>("codOrden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("documento_Fk")
                        .HasColumnType("int");

                    b.Property<string>("estadoOrden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaOrden")
                        .HasColumnType("datetime2");

                    b.Property<int>("metodoPago_FK")
                        .HasColumnType("int");

                    b.Property<int>("user_FK")
                        .HasColumnType("int");

                    b.HasKey("orden_id");

                    b.HasIndex("Tbl_Documentodocumento_id");

                    b.HasIndex("Tbl_MetodoPagometodoPago_id");

                    b.HasIndex("Tbl_Userusuario_id");

                    b.ToTable("tbl_Orden");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Producto", b =>
                {
                    b.Property<int>("producto_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Tbl_Menumenu_id")
                        .HasColumnType("int");

                    b.Property<string>("codProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estadoProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaCreacionP")
                        .HasColumnType("datetime2");

                    b.Property<int>("menu_Fk")
                        .HasColumnType("int");

                    b.Property<string>("nombreProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precioP")
                        .HasColumnType("float");

                    b.HasKey("producto_id");

                    b.HasIndex("Tbl_Menumenu_id");

                    b.ToTable("tbl_Producto");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_RolUsuario", b =>
                {
                    b.Property<int>("rolUser_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreRol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("rolUser_id");

                    b.ToTable("tbl_RolUsuarios");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_User", b =>
                {
                    b.Property<int>("usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Tbl_RolUsuariorolUser_id")
                        .HasColumnType("int");

                    b.Property<string>("apellidoU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contraU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correoU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rolUser_Fk")
                        .HasColumnType("int");

                    b.Property<int?>("tbl_Domiciliodomicilio_id")
                        .HasColumnType("int");

                    b.Property<int?>("telefonoU")
                        .HasColumnType("int");

                    b.HasKey("usuario_id");

                    b.HasIndex("Tbl_RolUsuariorolUser_id");

                    b.HasIndex("tbl_Domiciliodomicilio_id");

                    b.ToTable("tbl_User");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Carrito", b =>
                {
                    b.HasOne("FastFoodRestaurant.Entidades.tbl_Combo", "Tbl_Combo")
                        .WithMany("Tbl_Carritos")
                        .HasForeignKey("Tbl_Combomenu_id");

                    b.HasOne("FastFoodRestaurant.Entidades.tbl_Producto", "Tbl_Producto")
                        .WithMany("Tbl_Carritos")
                        .HasForeignKey("Tbl_Productoproducto_id");

                    b.HasOne("FastFoodRestaurant.Entidades.tbl_User", "Tbl_User")
                        .WithMany("Tbl_Carrito")
                        .HasForeignKey("Tbl_Userusuario_id");

                    b.Navigation("Tbl_Combo");

                    b.Navigation("Tbl_Producto");

                    b.Navigation("Tbl_User");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_DetalleCombo", b =>
                {
                    b.HasOne("FastFoodRestaurant.Entidades.tbl_Combo", "Tbl_Combo")
                        .WithMany("Tbl_DetalleCombos")
                        .HasForeignKey("Tbl_Combomenu_id");

                    b.HasOne("FastFoodRestaurant.Entidades.tbl_Producto", "Tbl_Producto")
                        .WithMany("Tbl_DetalleCombos")
                        .HasForeignKey("Tbl_Productoproducto_id");

                    b.Navigation("Tbl_Combo");

                    b.Navigation("Tbl_Producto");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_DetalleOrden", b =>
                {
                    b.HasOne("FastFoodRestaurant.Entidades.tbl_Combo", "Tbl_Combo")
                        .WithMany("Tbl_DetalleOrdens")
                        .HasForeignKey("Tbl_Combomenu_id");

                    b.HasOne("FastFoodRestaurant.Entidades.tbl_Orden", "Tbl_Orden")
                        .WithMany("Tbl_DetalleOrdens")
                        .HasForeignKey("Tbl_Ordenorden_id");

                    b.HasOne("FastFoodRestaurant.Entidades.tbl_Producto", "Tbl_Producto")
                        .WithMany("Tbl_DetalleOrdens")
                        .HasForeignKey("Tbl_Productoproducto_id");

                    b.Navigation("Tbl_Combo");

                    b.Navigation("Tbl_Orden");

                    b.Navigation("Tbl_Producto");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Orden", b =>
                {
                    b.HasOne("FastFoodRestaurant.Entidades.tbl_Documento", "Tbl_Documento")
                        .WithMany("Tbl_Orden")
                        .HasForeignKey("Tbl_Documentodocumento_id");

                    b.HasOne("FastFoodRestaurant.Entidades.tbl_MetodoPago", "Tbl_MetodoPago")
                        .WithMany("Tbl_Orden")
                        .HasForeignKey("Tbl_MetodoPagometodoPago_id");

                    b.HasOne("FastFoodRestaurant.Entidades.tbl_User", "Tbl_User")
                        .WithMany("Tbl_Orden")
                        .HasForeignKey("Tbl_Userusuario_id");

                    b.Navigation("Tbl_Documento");

                    b.Navigation("Tbl_MetodoPago");

                    b.Navigation("Tbl_User");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Producto", b =>
                {
                    b.HasOne("FastFoodRestaurant.Entidades.tbl_Menu", "Tbl_Menu")
                        .WithMany("Tbl_Producto")
                        .HasForeignKey("Tbl_Menumenu_id");

                    b.Navigation("Tbl_Menu");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_User", b =>
                {
                    b.HasOne("FastFoodRestaurant.Entidades.tbl_RolUsuario", "Tbl_RolUsuario")
                        .WithMany("Tbl_User")
                        .HasForeignKey("Tbl_RolUsuariorolUser_id");

                    b.HasOne("FastFoodRestaurant.Entidades.tbl_Domicilio", null)
                        .WithMany("Tbl_User")
                        .HasForeignKey("tbl_Domiciliodomicilio_id");

                    b.Navigation("Tbl_RolUsuario");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Combo", b =>
                {
                    b.Navigation("Tbl_Carritos");

                    b.Navigation("Tbl_DetalleCombos");

                    b.Navigation("Tbl_DetalleOrdens");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Documento", b =>
                {
                    b.Navigation("Tbl_Orden");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Domicilio", b =>
                {
                    b.Navigation("Tbl_User");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Menu", b =>
                {
                    b.Navigation("Tbl_Producto");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_MetodoPago", b =>
                {
                    b.Navigation("Tbl_Orden");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Orden", b =>
                {
                    b.Navigation("Tbl_DetalleOrdens");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_Producto", b =>
                {
                    b.Navigation("Tbl_Carritos");

                    b.Navigation("Tbl_DetalleCombos");

                    b.Navigation("Tbl_DetalleOrdens");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_RolUsuario", b =>
                {
                    b.Navigation("Tbl_User");
                });

            modelBuilder.Entity("FastFoodRestaurant.Entidades.tbl_User", b =>
                {
                    b.Navigation("Tbl_Carrito");

                    b.Navigation("Tbl_Orden");
                });
#pragma warning restore 612, 618
        }
    }
}
